version: "3.7"
services:
  flask:
    build: flask
    restart: always
    ports:
      - 5000
    networks:
      - flask_network

  nginx:
    build: nginx
    restart: always
    depends_on:
      - flask  
    ports:
      - 80:80
    networks:
      - flask_network

networks:
  flask_network:
